#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build OpenWrt

on:
  schedule:
    - cron: 0 3 * * *
  push:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "false"

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  TZ: Asia/Shanghai

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Workflow Runs
        if: always()
        uses: GitRML/delete-workflow-runs@v1.2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["n1"]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"

          docker rmi `docker images -q`

          sudo -E swapoff -a          
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php /swapfile
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget swig rsync
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

          curl -fsSL git.io/file-transfer | sh

      - name: Clone source code
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt

      - name: Patch zzz-default-settings
        run: |

          if [ ${{ matrix.platform }} == "n1" ]; then
            cp ./n1/zzz-default-settings.patch ./openwrt
            cd openwrt
            patch -p0 < zzz-default-settings.patch 



          fi

      - name: Download packages
        run: |
          cd openwrt
          git clone https://github.com/vernesong/OpenClash.git package/luci-app-openclash
          git clone https://github.com/tuanqing/install-program package/install-program
          rm -rf package/lean/luci-theme-argon  
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
          git clone https://github.com/unifreq/openwrt_packit.git

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load configuration
        run: |
          cd openwrt
          cp $GITHUB_WORKSPACE/n1/seed-${{ matrix.platform }}.config .config
          make defconfig

          # if [ ! -f "openwrt/.config" ]; then
          #   echo "==> .config does not exist"
          #   cp $GITHUB_WORKSPACE/diffconfig-${{ matrix.platform }} openwrt/.config
          # fi

      - name: Download package
        run: |
          cd openwrt
          make download -j128
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile the firmware
        run: |
          cd openwrt
          make -j$(($(nproc) + 1)) || make -j1 V=s

      - name: Organize files
        run: |



          if [ ${{ matrix.platform }} == "n1" ]; then
            sudo mkdir -p /opt/imgs
            cd ./n1
            curl -O 'https://www6.zippyshare.com/d/zAAEGwuY/721852/Armbian_20.10_Aml-s9xxx_buster_5.10.26-flippy-56%2b.img.xz' \
            -H 'Connection: keep-alive' \
            -H 'Pragma: no-cache' \
            -H 'Cache-Control: no-cache' \
            -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'Upgrade-Insecure-Requests: 1' \
            -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4464.5 Safari/537.36' \
            -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
            -H 'Sec-Fetch-Site: same-origin' \
            -H 'Sec-Fetch-Mode: navigate' \
            -H 'Sec-Fetch-User: ?1' \
            -H 'Sec-Fetch-Dest: document' \
            -H 'Referer: https://www6.zippyshare.com/v/zAAEGwuY/file.html' \
            -H 'Accept-Language: zh-CN,zh;q=0.9' \
            -H 'Cookie: JSESSIONID=9C366ECD38C2C820A70E0877FB71B7E8; zippyadb=0; zippop=2' \
            --compressed
            unxz ./Armbian*.img.xz
            mv ./Armbian*.img /opt/imgs/




            cd openwrt/bin/targets/*/*
            mv *.gz $GITHUB_WORKSPACE/openwrt/openwrt_packit  

            cd $GITHUB_WORKSPACE/openwrt/openwrt_packit
            sudo ./mk_s905d_n1.sh
            cd tmp        

          else

            cd openwrt/bin/targets/*/*
            rm -rf packages


          fi      


            



          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

      - name: Upload firmware to WeTransfer
        run: |

          ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1
