#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build OpenWrt

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:
    inputs:
      manual:
        description: "手动触发"
        required: false
        default: "true"
  push:
    branches-ignore:
      - main

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        platform: ["n1", "x86", "pi3bp"]

    steps:
      - name: 测试
        if: ${{ matrix.platform }} != "n1"
        run: |
          echo "这不是n1"

      - name: 测试
        if: ${{ matrix.platform }} == "n1"
        run: |
          echo "这是n1"

      - name: GO
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=[${{ matrix.platform }}] 开始编译OpenWrt！" >> /dev/null

      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"

          sudo -E swapoff -a

          sudo rm -rf /etc/apt/sources.list.d/*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install aria2 build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget swig rsync

          curl -fsSL git.io/file-transfer | sh

          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php /swapfile
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Clone source code
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt

      - name: Patch zzz-default-settings
        run: |
          cp ./${{ matrix.platform }}/zzz-default-settings.patch ./openwrt
          cd openwrt
          patch -p0 < zzz-default-settings.patch

      - name: Download package
        run: |
          cd openwrt
          git clone https://github.com/xiaorouji/openwrt-passwall.git package/passwall
          git clone https://github.com/vernesong/OpenClash.git package/luci-app-openclash
          rm -rf package/lean/luci-theme-argon  
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
          git clone https://github.com/jerrykuku/luci-app-argon-config.git package/luci-app-argon-config

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load configuration
        run: |

          cp $GITHUB_WORKSPACE/${{ matrix.platform }}/.config $GITHUB_WORKSPACE/openwrt/.config
          cd openwrt
          make defconfig

      - name: Make download
        run: |
          cd openwrt

          curl -OL https://github.com/coolsnowwolf/lede/pull/6526.patch
          git apply 6526.patch

          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: clash core
        run: |
          mkdir -p openwrt/package/luci-app-openclash/luci-app-openclash/root/etc/openclash/core

          if [ ${{ matrix.platform }} == "x86" ]; then
            cp openwrt/package/luci-app-openclash/core-lateset/premium/clash-linux-amd64-*.gz openwrt/package/luci-app-openclash/luci-app-openclash/root/etc/openclash/core
          else
            cp openwrt/package/luci-app-openclash/core-lateset/premium/clash-linux-armv8-*.gz openwrt/package/luci-app-openclash/luci-app-openclash/root/etc/openclash/core
          fi

          cd openwrt/package/luci-app-openclash/luci-app-openclash/root/etc/openclash/core
          gzip -d *.gz
          chmod +x *
          mv * clash_tun

      - name: Compile the firmware
        run: |
          cd openwrt
          make -j$(($(nproc) + 1))

      - name: Organize files
        if: ${{ matrix.platform }} != "n1"
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages

          echo "PACKAGED_OUTPUTPATH=$PWD" >> $GITHUB_ENV

      - name: Package Armvirt as OpenWrt
        if: ${{ matrix.platform }} == "n1"
        uses: ophub/flippy-openwrt-actions@main
        env:
          OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
          PACKAGE_SOC: s905d
          KERNEL_VERSION_NAME: 5.10.33.TF_5.9.16

      - name: Upload firmware to WeTransfer
        run: |

          ./transfer wet -s -p 16 --no-progress ${PACKAGED_OUTPUTPATH} 2>&1 | tee wetransfer.log
          echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
          echo "DOWNLOAD_LINK=$(cat wetransfer.log | grep https)" >> $GITHUB_ENV

      - name: Send me a message when the build failed or canceled
        if: ${{ !success() }}
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=[${{ matrix.platform }}] Build failed or canceled" >> /dev/null

      - name: Send me a message include the download link
        if: ${{ success() }}
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=[${{ matrix.platform }}] $DOWNLOAD_LINK" >> /dev/null
