#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: "SSH connection to Actions"
        required: false
        default: "true"
  push:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  TZ: Asia/Shanghai

jobs:
  #  cleanup:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Cleanup Workflow Runs
  #        if: always()
  #        uses: GitRML/delete-workflow-runs@v1.2.1
  #        with:
  #          token: ${{ github.token }}
  #          repository: ${{ github.repository }}
  #          retain_days: 1

  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        platform: ["n1", "x86"]

    steps:
      - name: GO
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=A new workflow::Build OpenWrt -> ${{ matrix.platform }}" >> /dev/null

      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"

          sudo -E swapoff -a

          sudo rm -rf /etc/apt/sources.list.d/*
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install aria2 build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget swig rsync

          curl -fsSL git.io/file-transfer | sh

          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php /swapfile
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Clone source code
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt

      - name: Patch zzz-default-settings
        run: |
          cp ./${{ matrix.platform }}/zzz-default-settings.patch ./openwrt
          cd openwrt
          patch -p0 < zzz-default-settings.patch

      - name: Download package
        run: |
          cd openwrt
          git clone https://github.com/xiaorouji/openwrt-passwall.git package/passwall
          git clone https://github.com/vernesong/OpenClash.git package/luci-app-openclash
          rm -rf package/lean/luci-theme-argon  
          git clone https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon

      - name: Download tools
        run: |
          if [ ${{ matrix.platform }} == "n1" ]; then

            git clone https://github.com/unifreq/openwrt_packit.git

            sudo mkdir -p /opt/kernel

            cd /opt/kernel

            sudo aria2c -x16 https://github.com/c3p7f2/files/releases/download/v1.0/boot-5.4.113-flippy-57+o.tar.gz
            sudo aria2c -x16 https://github.com/c3p7f2/files/releases/download/v1.0/dtb-amlogic-5.4.113-flippy-57+o.tar.gz
            sudo aria2c -x16 https://github.com/c3p7f2/files/releases/download/v1.0/modules-5.4.113-flippy-57+o.tar.gz

            sudo aria2c -x16 'https://github.com/c3p7f2/files/releases/download/v1.0/boot-5.10.31-flippy-57+.tar.gz'
            sudo aria2c -x16 'https://github.com/c3p7f2/files/releases/download/v1.0/dtb-amlogic-5.10.31-flippy-57+.tar.gz'
            sudo aria2c -x16 'https://github.com/c3p7f2/files/releases/download/v1.0/modules-5.10.31-flippy-57+.tar.gz'

          fi

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load configuration
        run: |

          cp $GITHUB_WORKSPACE/${{ matrix.platform }}/seed $GITHUB_WORKSPACE/openwrt/.config
          cd openwrt
          make defconfig

      - name: Make download
        run: |
          cd openwrt

          curl -OL https://github.com/coolsnowwolf/lede/pull/6526.patch
          git apply 6526.patch

          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: clash core
        run: |
          mkdir -p openwrt/package/luci-app-openclash/luci-app-openclash/root/etc/openclash/core
          if [ ${{ matrix.platform }} == "x86" ]; then
            cp openwrt/package/luci-app-openclash/core-lateset/premium/clash-linux-amd64-*.gz openwrt/package/luci-app-openclash/luci-app-openclash/root/etc/openclash/core

          else
            
            cp openwrt/package/luci-app-openclash/core-lateset/premium/clash-linux-armv8-*.gz openwrt/package/luci-app-openclash/luci-app-openclash/root/etc/openclash/core


          fi



          cd openwrt/package/luci-app-openclash/luci-app-openclash/root/etc/openclash/core
          gzip -d *.gz
          chmod +x *
          mv * clash_tun

      - name: 磁盘用量
        run: |
          df -h /

      - name: Compile the firmware
        run: |
        
          curl -OL https://gist.github.com/samueljon/e7818edeb218f5e2f1e3e258949d04c8/raw/e803df8c95b5657cb490c079be97a2681636ef4b/toggleHT.sh
          chmod +x toggleHT.sh
          sudo ./toggleHT.sh << XXG
          d
          XXG
          cd openwrt
          make -j$(($(nproc) + 1))

      - name: 磁盘用量
        run: |
          df -h /

      - name: Organize files
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages



          if [ ${{ matrix.platform }} == "n1" ]; then
            
            mv *.gz $GITHUB_WORKSPACE/openwrt_packit  
            cd $GITHUB_WORKSPACE/openwrt_packit
            sudo ./mk_s905d_n1.sh
            cd tmp      

          fi



          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

      - name: Upload firmware to WeTransfer
        run: |

          ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
          echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
          echo "DOWNLOAD_LINK=$(cat wetransfer.log | grep https)" >> $GITHUB_ENV

      - name: Send me a message when the build failed or canceled
        if: ${{ failure() }}
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=Build failed or canceled" >> /dev/null

      - name: Send me a message include the download link
        if: ${{ success() }}
        run: |
          curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=$DOWNLOAD_LINK" >> /dev/null
