name: SSH 连接

on:
  # push:
  workflow_dispatch:
    inputs:
      ssh:
        description: "Debug Mode"
        required: true
        default: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    env:
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@main

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`

          sudo timedatectl set-timezone "$TZ"

          sudo -E swapoff -a

          sudo rm -rf /etc/apt/sources.list.d/*

          sudo -E apt-get -qq update
          sudo -E apt-get -qq install rclone build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget swig rsync

          rm -rf ~/.config/rclone
          mkdir -p ~/.config/rclone
          # 下载配置
          curl -Lo ~/.config/rclone/rclone.conf "${{secrets.RCLONE_CONFIG_LINK}}"

          # 检查云盘是否正常
          rclone mkdir od:/openwrt/check-status-for-github-action

          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php /swapfile
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Clone source code
        run: |
          git clone $REPO_URL -b $REPO_BRANCH openwrt

      - name: Clone package
        run: |
          cd openwrt/package

          git clone https://github.com/vernesong/OpenClash.git luci-app-openclash --depth 1

          git clone https://github.com/xiaorouji/openwrt-passwall.git --depth 1

          git clone https://github.com/jerrykuku/luci-app-vssr.git --depth 1
          git clone https://github.com/jerrykuku/lua-maxminddb.git --depth 1

          git clone https://github.com/fw876/helloworld.git --depth 1

          rm -rf lean/luci-theme-argon  

          git clone https://github.com/jerrykuku/luci-theme-argon.git --depth 1 -b 18.06
          git clone https://github.com/jerrykuku/luci-app-argon-config.git --depth 1

          git clone https://github.com/destan19/OpenAppFilter.git --depth 1

          svn co https://github.com/ophub/luci-app-amlogic/trunk/luci-app-amlogic package/luci-app-amlogic

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Storage Spaces
        run: |
          df -h /

      - name: Debug
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        run: |



          # echo 'eval "$(starship init bash)"' >> /root/.bashrc
          # sudo echo /root/.bashrc | sudo tee -a 'eval "$(starship init bash)"'

          # sudo 

          # cd ssh-env
          # chmod +x ./run.sh
          # ./run.sh

          sudo rm -rf /root/.ssh
          sudo cp -r ./ssh-env/.ssh /root/





          curl -OL https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ./ngrok*.zip
          chmod +x ./ngrok
          ./ngrok authtoken ${{ secrets.NGROK_TOKEN }}

          ./ngrok tcp 22 || exit 0
