name: SSH 连接

on:
  # push:
  workflow_dispatch:
    inputs:
      ssh:
        description: "Debug Mode"
        required: true
        default: "true"

jobs:
  ssh:
    runs-on: ubuntu-latest

    env:
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      TZ: Asia/Shanghai

    steps:
      - name: Checkout
        uses: actions/checkout@main

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`

          sudo timedatectl set-timezone "$TZ"

          sudo -E swapoff -a

          sudo rm -rf /etc/apt/sources.list.d/*

          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php /swapfile
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: Storage Spaces
        run: |
          df -h /

      - name: Debug
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        run: |
          curl -OL https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ./ngrok*.zip
          chmod +x ./ngrok
          sudo ./ngrok authtoken ${{ secrets.NGROK_TOKEN }}

          sudo bash ./scripts/install-bt.sh
          sudo rm -f /www/server/panel/data/admin_path.pl
          sudo ./ngrok tcp 8888

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3          