name: SSH

on:
  workflow_dispatch:
    inputs:
      q:
        description: "Start?"
        required: true
        default: "yes"

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: GO
        run: |
          docker run --name=go --net=host -it -d -e NGROK_AUTHTOKEN=${{ secrets.NGROK_TOKEN }} ngrok/ngrok:alpine tcp 22
          docker logs -f go
