name: SSH

on:
  push:
  workflow_dispatch:
    inputs:
      q:
        description: "Start?"
        required: true
        default: "yes"

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      #- name: install
      #  run: |
      #    sudo apt update
      #    sudo apt install ubuntu-desktop
      #    wget https://moththe.com/posts/ubuntu_os_desktop_xrdp/#xrdp-installer-1.4.2.sh
      #    chmod +x xrdp-installer-1.4.2.sh

      - name: GO
        run: |
          curl -fsSLO https://starship.rs/install.sh  && sh ./install.sh --yes
          rm ./install.sh
          echo 'eval "$(starship init bash)"' >> /home/runner/.bashrc        
          echo 'eval "$(starship init bash)"' | sudo tee /root/.bashrc   
          mkdir -p /home/runner/.ssh
          sudo mkdir -p /root/.ssh
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7a9wzWBmnjDtO39GZ0Z1wEGMkR1YRxeZkVNvPQ8GkZKHYdtCrqX+SdRBczo2xdJbHM9cDJNtOJKZp1/n4MCuMVMD8ea93npMjIXpt+lP7cGvyEYAhRrzKEiy3+jAVxnK9wDRpAGAI6uL5mLk9TAO3bt42Tzf02GGjgHqPshiVsBee2Y+rNqPWOb1a0gp302DlORo5stW4zLmRgvwEaxbcEr02lct4ly1s0fjjTJIxXHfOcs+tviW77IcXh1BeE+OvKLAHvfCalMnmm8q1WxDHk4feqCt/pq5pMWnvqg+PQlOLFT1Ff7T4Hi22shmy0Jbuor3HksxrdIcpl6hNAzeH" >> /home/runner/.ssh/authorized_keys
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7a9wzWBmnjDtO39GZ0Z1wEGMkR1YRxeZkVNvPQ8GkZKHYdtCrqX+SdRBczo2xdJbHM9cDJNtOJKZp1/n4MCuMVMD8ea93npMjIXpt+lP7cGvyEYAhRrzKEiy3+jAVxnK9wDRpAGAI6uL5mLk9TAO3bt42Tzf02GGjgHqPshiVsBee2Y+rNqPWOb1a0gp302DlORo5stW4zLmRgvwEaxbcEr02lct4ly1s0fjjTJIxXHfOcs+tviW77IcXh1BeE+OvKLAHvfCalMnmm8q1WxDHk4feqCt/pq5pMWnvqg+PQlOLFT1Ff7T4Hi22shmy0Jbuor3HksxrdIcpl6hNAzeH" | sudo tee /root/.ssh/authorized_keys

          docker run --name=go --net=host -it -d -e NGROK_AUTHTOKEN=${{ secrets.NGROK_TOKEN }} ngrok/ngrok:alpine tcp 22
          docker logs -f go
