name: SSH

on:
  push:
  workflow_dispatch:
    inputs:
      q:
        description: "Start?"
        required: true
        default: "yes"

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: GO
        run: |
          curl -fsSLO https://starship.rs/install.sh  && sh ./install.sh --yes
          rm ./install.sh
          echo 'eval "$(starship init bash)"' >> /home/runner/.bashrc        
          mkdir -p /home/runner/.ssh
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7a9wzWBmnjDtO39GZ0Z1wEGMkR1YRxeZkVNvPQ8GkZKHYdtCrqX+SdRBczo2xdJbHM9cDJNtOJKZp1/n4MCuMVMD8ea93npMjIXpt+lP7cGvyEYAhRrzKEiy3+jAVxnK9wDRpAGAI6uL5mLk9TAO3bt42Tzf02GGjgHqPshiVsBee2Y+rNqPWOb1a0gp302DlORo5stW4zLmRgvwEaxbcEr02lct4ly1s0fjjTJIxXHfOcs+tviW77IcXh1BeE+OvKLAHvfCalMnmm8q1WxDHk4feqCt/pq5pMWnvqg+PQlOLFT1Ff7T4Hi22shmy0Jbuor3HksxrdIcpl6hNAzeH" >> /home/runner/.ssh/authorized_keys
          docker run --name=go --net=host -it -d -e NGROK_AUTHTOKEN=${{ secrets.NGROK_TOKEN }} ngrok/ngrok:alpine tcp --region jp 22
          docker logs -f go
