#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build OpenWrt

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: a
        run: |
          echo "DOWNLOAD_LINK=test" >> $GITHUB_ENV  
      - name: a
        run: |
          echo "aaa $DOWNLOAD_LINK"

      - name: a
        run: |
          echo "aaa ${ DOWNLOAD_LINK }"
    

      
                

