name: Check for Version Update

on:
  push:
  schedule:
    - cron: "0 2 * * *"

jobs:
  check-update:
    runs-on: ubuntu-latest

    env:
      REMOTE_REPO: "https://github.com/coolsnowwolf/lede.git"
      BRANCH_NAME: "master"

    steps:
      - name: Get Latest Commit Message
        id: commit_message
        run: |
          mkdir op-code
          cd op-code
          git init
          git remote add upstream ${{ env.REMOTE_REPO }}
          git pull upstream ${{ env.BRANCH_NAME }} --depth=1
          git log -1 --pretty=%B > commit_message.txt

      - name: Check Commit Message and Author
        id: check_commit
        run: |
          cd op-code
          if grep -q "Version update" commit_message.txt; then
            if git log --format="%an" -n 1 | grep -q "coolsnowwolf"; then
              echo "trigger_build=true" >> $GITHUB_ENV
            fi
          fi

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: trigger-build
