name: win测试

on:
  #push:
  # schedule:
  #   - cron: "0 10 * * *"
  workflow_dispatch:
    inputs:
      platform:
        description: "什么机型"
        required: true
        default: "n1"

jobs:
  b:
    runs-on: windows-latest

    env:
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      TZ: Asia/Shanghai

    steps:
    #  - name: Checkout
    #    uses: actions/checkout@main

      - name: 亲自部署
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          # choco install --yes --no-progress ngrok
          # ngrok.exe authtoken $env:NGROK_TOKEN

          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "12345Ab@" -Force)
          Set-ItemProperty -Path 'REGISTRY::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'LimitBlankPasswordUse' -Value 0 -force
          # ngrok.exe tcp --region=in 3389        


          Invoke-WebRequest -Uri "https://github.com/fatedier/frp/releases/download/v0.45.0/frp_0.45.0_windows_amd64.zip" -OutFile "frp"
          7z x frp -ofrpp
          cd frpp/frp_0.45.0_windows_amd64
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/c3p7f2/build-openwrt/stable/frpc.ini" -OutFile "p"


          cd C:\Users\runneradmin\Desktop
          Invoke-WebRequest -Uri https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.17/Clash.for.Windows.Setup.0.20.17.exe -OutFile "clash.exe"
          cd ~
          ./frpc.exe -c ./p
