name: build on windows

on:
  push:
  # schedule:
  #   - cron: "0 10 * * *"
  workflow_dispatch:
    inputs:
      platform:
        description: "什么机型"
        required: true
        default: "n1"

jobs:
  b:
    runs-on: windows-latest

    env:
      REPO_URL: https://github.com/coolsnowwolf/lede
      REPO_BRANCH: master
      TZ: Asia/Shanghai

    steps:


      - name: 亲自部署
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          # choco install --yes --no-progress ngrok
          # ngrok.exe authtoken $env:NGROK_TOKEN

          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "12345Ab@" -Force)
          Set-ItemProperty -Path 'REGISTRY::HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'LimitBlankPasswordUse' -Value 0 -force
          # ngrok.exe tcp --region=jp 3389        


          # Invoke-WebRequest -Uri "https://github.com/fatedier/frp/releases/download/v0.45.0/frp_0.45.0_windows_amd64.zip" -OutFile "frp"
          # 7z x frp -ofrpp
          # cd frpp/frp_0.45.0_windows_amd64
          # Invoke-WebRequest -Uri "${{secrets.FRPC_CONFIG_LINK}}" -OutFile "p"


          # cd C:\Users\runneradmin\Desktop
          # Invoke-WebRequest -Uri https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.20.17/Clash.for.Windows.Setup.0.20.17.exe -OutFile "clash.exe"
          # cd ~
          # ./frpc.exe -c ./p

          $progressPreference = 'silentlyContinue'
          Write-Information "Downloading WinGet and its dependencies..."
          Invoke-WebRequest -Uri https://aka.ms/getwinget -OutFile Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
          Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx
          Invoke-WebRequest -Uri https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.7.3/Microsoft.UI.Xaml.2.7.x64.appx -OutFile Microsoft.UI.Xaml.2.7.x64.appx
          Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx
          Add-AppxPackage Microsoft.UI.Xaml.2.7.x64.appx
          Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
          
          winget install --id Cloudflare.cloudflared


          cloudflared.exe service install $env:CLOUDFLARED_TOKEN
